version: "3"
services:
  provisioner:
    image: "provisioner:latest"
    # image: "534003348933.dkr.ecr.eu-west-1.amazonaws.com/provisioner:main"
    # entrypoint: "sh db-init.sh"
    ports:
      - "9000:8080"
    depends_on:
      - "db"

  db:
    image: "amazon/dynamodb-local"
    ports:
      - "8000:8000"
